version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: product_db
    ports:
      - '5432:5432'

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:123456@db:5432/product_db?schema=public'
